spring:
  application:
    name: Spring3SecurityBack
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: EDU
    password: EDU
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  jwt:
    secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff # secret-key를 secret으로 변경
      
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 1h
  port: 8383
  error:
    include-message: always
